/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/complexT3.gltf')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <mesh name="u_pillar" geometry={nodes.u_pillar.geometry} material={materials.Material} position={[0, 1, 0]} />
        <mesh name="u_head" geometry={nodes.u_head.geometry} material={materials.Material} position={[0, 2.5, 0]}>
          <group name="f_0" position={[0, 0.5, 0]} />
          <group name="f_1" position={[0.5, 0, 0]} rotation={[Math.PI, 0, -Math.PI / 2]} />
          <group name="f_2" position={[0, 0, -0.5]} rotation={[-Math.PI / 2, -Math.PI / 2, 0]} />
          <group name="f_3" position={[-0.5, 0, 0]} rotation={[0, 0, Math.PI / 2]} />
          <group name="f_4" position={[0, 0, 0.5]} rotation={[Math.PI / 2, Math.PI / 2, 0]} />
        </mesh>
        <mesh name="u_base" geometry={nodes.u_base.geometry} material={materials.Material} position={[0, 0.5, 0]} />
        <mesh name="Torus" geometry={nodes.Torus.geometry} material={materials['Material.001']} position={[0, 2.88, 0]} scale={[0.56, 0.49, 0.56]} />
        <mesh name="Torusbottom001" geometry={nodes.Torusbottom001.geometry} material={materials['Material.001']} scale={[1, 0, 1]} />
        <mesh name="Torusbottom002" geometry={nodes.Torusbottom002.geometry} material={materials['Material.001']} scale={[1, 0, 1]} />
        <mesh name="Torusbottom003" geometry={nodes.Torusbottom003.geometry} material={materials['Material.001']} scale={[1, 0, 1]} />
        <mesh name="Torusbottom004" geometry={nodes.Torusbottom004.geometry} material={materials['Material.001']} scale={[1, 0, 1]} />
      </group>
    </group>
  )
}

useGLTF.preload('/complexT3.gltf')
