/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/smoothT.gltf')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <mesh name="u_head" geometry={nodes.u_head.geometry} material={materials.YG}>
          <group name="f_0" position={[0, 3.4, 0]} />
          <group name="f_1" position={[1, 2.4, 0]} rotation={[Math.PI, 0, -Math.PI / 2]} />
          <group name="f_2" position={[0, 2.4, -1]} rotation={[-Math.PI / 2, -Math.PI / 2, 0]} />
          <group name="f_3" position={[-1, 2.4, 0]} rotation={[0, 0, Math.PI / 2]} />
          <group name="f_4" position={[0, 2.4, 1]} rotation={[Math.PI / 2, Math.PI / 2, 0]} />
        </mesh>
        <mesh name="joint" geometry={nodes.joint.geometry} material={materials.Material} scale={0.31} />
        <mesh name="Torus" geometry={nodes.Torus.geometry} material={materials.YG} />
        <mesh name="Torus_bottom_001" geometry={nodes.Torus_bottom_001.geometry} material={materials.YG} rotation={[-Math.PI, 0, -Math.PI]} scale={0} />
        <mesh name="Torus_bottom_002" geometry={nodes.Torus_bottom_002.geometry} material={materials.YG} rotation={[-Math.PI, 0, -Math.PI]} scale={0} />
        <mesh name="Torus_bottom_003" geometry={nodes.Torus_bottom_003.geometry} material={materials.YG} rotation={[-Math.PI, 0, -Math.PI]} scale={0} />
        <mesh name="Torus_bottom_004" geometry={nodes.Torus_bottom_004.geometry} material={materials.YG} rotation={[-Math.PI, 0, -Math.PI]} scale={0} />
      </group>
    </group>
  )
}

useGLTF.preload('/smoothT.gltf')
